<html><head>
<meta charset='UTF-8'>
<link href='resource/bootstrap.min.css' rel='Stylesheet' type='text/css' />
<link href='resource/style.css' rel='Stylesheet' type='text/css' />
</head>
<body>
<div id='page'>
<h1 class='entry-title'>[Service Fabric] SF node fails to read DNS conf and fix</h1>
 <a class='url fn n profile-usercard-hover' href='https://social.msdn.microsoft.com/profile/Maheshk [MSFT]' target='_blank'>Maheshk [MSFT]</a>
<time>    12/18/2016 1:06:00 AM</time>
<hr>
<div id='content'><p><font style="background-color: #ffffff">Recently SF developer reported this problem where his Azure Service Fabric &gt; <em>ImageStoreService(ISS)</em> displayed a warning message due to one his secondary node down. This node was “down” all sudden without any change to his cluster/application. </font>From the SF Explorer portal, we do noticed a brief warning message saying due to some unhealthy event, this node is down. </p> <p><font style="background-color: #ffff00"><strong>SF Explorer - warning</strong> </font></p> <p><a href="media/2016/12/image455.png"><img title="image" style="border-left-width: 0px;border-right-width: 0px;border-bottom-width: 0px;float: none;padding-top: 0px;padding-left: 0px;margin-left: auto;padding-right: 0px;border-top-width: 0px;margin-right: auto" border="0" alt="image" src="media/2016/12/image_thumb406.png" width="878" height="483"></a></p> <p><strong><font style="background-color: #ffff00">Error message</font></strong></p> <p><font color="#666666" size="2" face="Consolas">Unhealthy event: SourceId='System.PLB', Property='ServiceReplicaUnplacedHealth_Secondary_00000000-0000-0000-0000-000000003000', HealthState='Warning', ConsiderWarningAsError=false.<br>The Load Balancer was unable to find a placement for one or more of the Service's Replicas:<br>ImageStoreService Secondary Partition 00000000-0000-0000-0000-000000003000 could not be placed, possibly, due to the following constraints and properties:&nbsp; <br>TargetReplicaSetSize: 5<br>Placement Constraint: NodeTypeName==sf**type<br>Depended Service: ClusterManagerServiceName</font></p> <p><font color="#666666" size="2" face="Consolas">Constraint Elimination Sequence:<br>ReplicaExclusionStatic eliminated 3 possible node(s) for placement -- 2/5 node(s) remain.<br>PlacementConstraint + ServiceTypeDisabled/NodesBlockListed eliminated 0 + 1 = 1 possible node(s) for placement -- 1/5 node(s) remain.<br>ReplicaExclusionDynamic eliminated 1 possible node(s) for placement -- 0/5 node(s) remain.</font></p> <p><font color="#666666" size="2" face="Consolas">Nodes Eliminated By Constraints:</font></p> <p><font color="#666666" size="2" face="Consolas">ReplicaExclusionStatic -- No Colocations with Partition's Existing Secondaries/Instances:<br>FaultDomain:fd:/1 NodeName:_sf**type_1 NodeType:sf**type NodeTypeName:sf**type UpgradeDomain:1 UpgradeDomain: ud:/1 Deactivation Intent/Status: None/None<br>FaultDomain:fd:/4 NodeName:_sf**type_4 NodeType:sf**type NodeTypeName:sf**type UpgradeDomain:4 UpgradeDomain: ud:/4 Deactivation Intent/Status: None/None<br>FaultDomain:fd:/3 NodeName:_sf**type_3 NodeType:sf**type NodeTypeName:sf**type UpgradeDomain:3 UpgradeDomain: ud:/3 Deactivation Intent/Status: None/None</font></p> <p><font color="#666666" size="2" face="Consolas">PlacementConstraint + ServiceTypeDisabled/NodesBlockListed -- PlacementProperties must Satisfy Service's PlacementConstraint, and Nodes must not have had the ServiceType Disabled or be BlockListed due to Node's Pause/Deactivate Status:<br>FaultDomain:fd:/2 NodeName:_sf**type_2 NodeType:sf**type NodeTypeName:sf**type UpgradeDomain:2 UpgradeDomain: ud:/2 Deactivation Intent/Status: None/None</font></p> <p><font face="Consolas"><font color="#666666" size="2">ReplicaExclusionDynamic -- No Colocations with Partition's Existing Primary or Potential Secondaries:<br><br>FaultDomain:fd:/0 NodeName:_sf**type_0 NodeType:sf**type NodeTypeName:sf**type UpgradeDomain:0 UpgradeDomain: ud:/0 Deactivation Intent/Status: None/None</font><br><strong><font style="background-color: #ffff00"></font></strong></font></p> <p><strong><font style="background-color: #ffff00">Noticed below health warning event</font> </strong></p> <p><font color="#666666" size="2" face="Consolas">There was no data from ‘sf**type_2’ post that failing date, so we confirmed both ISS and FabricDCA.exe was crashing<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; N/S RD sf**type_3 Up 131212...946953<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; N/S RD sf**type_1 Up 131212...593463858<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; N/S RD sf**type_4 Up 13121.....3859<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <font style="background-color: #ffff00">&nbsp;&nbsp;&nbsp; N/I SB sf**type_2 Down 1312.....63860</font><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; N/P RD sf**type_0 Up 131212.....61</font></p> <p><font color="#666666"></font> <p><strong><font style="background-color: #ffff00" color="#666666">Event Log</font></strong></p> <p><font size="2" face="Consolas"><font color="#666666">Log Name:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Application<br>Source:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Microsoft-Windows-PerfNet<br>Date:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 12/9/2016 7:42:40 AM<br>Event ID:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2005<br>Task Category: None<br>Level:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Error<br>Keywords:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Classic<br>User:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; N/A<br>Computer:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; sf***ype00xxx02<br>Description:<br><font style="background-color: #ffff00">Unable to read performance data for the Server service. The first four bytes (DWORD) of the Data section contains the status code, the second four bytes contains the IOSB.Status and the next four bytes contains the IOSB.Information.</font></font></font></p> <p><font color="#666666" size="2" face="Consolas">C0000466 00000000 634A41F0 <br>Log Name:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Microsoft-ServiceFabric/Admin<br>Source:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Microsoft-ServiceFabric<br>Date:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 12/12/2016 11:29:13 AM<br>Event ID:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 59904<br>Task Category: FabricDCA<br>Level:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Error<br>Keywords:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Default<br>User:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; NETWORK SERVICE<br>Computer:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; sf***ype00xxx02</font></p> <p><font color="#666666" size="2" face="Consolas">Description:<br>Failed to copy file D:\\SvcFab\Log\PerformanceCounters_ServiceFabricPerfCounter\fabric_counters_6361xxxxx47065191_000940.blg to Azure blob account sf***ype00xxx02, container fabriccounters-2b73743xxxxxxa46d111c4d5.</font></p> <p><font face="Consolas"><font size="2"><font color="#666666"><font style="background-color: #ffff00">Microsoft.WindowsAzure.Storage.StorageException: The remote name could not be resolved: 'sf***ype00xxx02.blob.core.windows.net' ---&gt; System.Net.WebException: The remote name could not be resolved: 'sf***ype00xxx02.blob.core.windows.net'</font><br>&nbsp;&nbsp; at System.Net.HttpWebRequest.GetRequestStream(TransportContext&amp; context)<br>&nbsp;&nbsp; at System.Net.HttpWebRequest.GetRequestStream()<br>&nbsp;&nbsp; at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)<br>&nbsp;&nbsp; --- End of inner exception stack trace ---<br>&nbsp;&nbsp; at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)<br>&nbsp;&nbsp; at Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.UploadFromStreamHelper(Stream source, Nullable`1 length, AccessCondition accessCondition, BlobRequestOptions options, OperationContext operationContext)<br>&nbsp;&nbsp; at FabricDCA.AzureFileUploader.CreateStreamAndUploadToBlob(String sourceFile, CloudBlockBlob destinationBlob)<br>&nbsp;&nbsp; at FabricDCA.AzureFileUploader.CopyFileToDestinationBlobWorker(FileCopyInfo fileCopyInfo, CloudBlockBlob destinationBlob)<br>&nbsp;&nbsp; at FabricDCA.AzureFileUploader.CopyFileToDestinationBlob(Object context)<br>&nbsp;&nbsp; at System.Fabric.Dca.Utility.PerformWithRetries[T](Action`1 worker, T context, RetriableOperationExceptionHandler exceptionHandler, Int32 initialRetryIntervalMs, Int32 maxRetryCount, Int32 maxRetryIntervalMs)<br>&nbsp;&nbsp; at FabricDCA.AzureFileUploader.CopyFileToDestination(String source, String sourceRelative, Int32 retryCount, Boolean&amp; fileSkipped)</font></font></font></p> <p><font style="background-color: #ffff00"><strong>Check list tried:</strong></font></p> <ul> <li>we checked the free space details of drive “D:/” of this failing node – had enough space.  <li>we were able to RDP into the machine (failing node) but could not able to browse any web sites or nslookup any url. </li></ul> <ol> <ol> <li> <div><em><font size="2">&gt;nslookup sf***ype00xxx02.blob.core.windows.net </font></em></div> <li> <div><em><font size="2">&nbsp; server:unknown</font></em></div> <li> <div><font size="2">&nbsp;&nbsp; *** unknown can’t find sf***ype00xxx02.blob.core.windows.net: No response from server</font></div></li></ol></ol> <ul> <li>logs confirmed that, this particular failing node VM was going through some network related issue which is why it was not able to connect to any of the services and storage account.  <li>there were no fabric log post this issue start date which also confirmed this vm lost its connectivity  <li>checked any crash dump under D:\SvcFab\Log\CrashDumps – no dumps <br>checked the traces from D:\SvcFab\Log\Traces – did not get any hint </li></ul> <p><strong><font style="background-color: #ffff00">Fix/resolution:</font></strong></p> <ul> <li>With above all findings, we confirmed this failing node:_sf***ype_2 was not resolving the DNS for some reason. This issue occurs very rarely due to corruption at OS level.  <li>From the registry we see it has received the proper DNS settings from the azure DHCP server.&nbsp; <li>The “HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\DhcpNameServer” was set to 16x.6x.12x.1x” but the affected machine was not able to read and use this DNS configuration due to which name resolution was broken at the operating system.  <li>To overcome this issue, we ran <b>“Netsh&nbsp; int ip reset c:\reset.log”</b> and <b>“netsh winsock reset catalog”&nbsp; </b>to reset the IP stack and windows socket catalog and rebooted the Virtual machine which eventually resolved this issue. </li></ul> <p>Reference article :<a href="https://support.microsoft.com/en-us/kb/299357">https://support.microsoft.com/en-us/kb/299357</a></p> <p><em>Let me know if this helps in someway. </em></p></div>
</div></body>
<script type='text/javascript' src='resource/jquery-1.12.1.min.js'></script>
<script type='text/javascript' src='resource/replace.js'></script>
</html>
